config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'

  get 'about', to: 'welcome#about'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, length: { maximum: 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    
    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params) 
        if @article.save
            flash[:notice] = "Article successfully created"
            redirect_to article_path(@article)
        else
            render :new
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find_by(title: article_params[:title])
        updated_article = @article.update(article_params)
        if updated_article!
            flash[:notice] = "Article successfully updated"
            redirect_to article_path(updated_article)
        else
            render :edit
        end
    end

    def show
        @article = Article.find(params[:id])
    end

    def detroy
        @article = Article.find(params[:id])
        @article.detroy
    end

    private

    def article_params
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
    def home
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1> Update your article:</h1>

<% if @article.errors.any? %>
  <h2>Found the following errors when updating your article:</h2>
  <ul>
    <% @article.errors.full_messages.each do |err_msg| %>
        <li> <%= err_msg %> </li>
    <% end %>
  </ul>
<% end %>

<div>
  <%= form_for @article do |f|%>
    <p>
        <%= f.label :title %>
        </br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %>
        </br>
        <%= f.text_area :description %>
    </p>
    <%= f.submit %>
  <% end %>
</div>
</br></br>
<%= link_to 'Articles List', articles_path %>

app/views/articles/index.html.erb
<h1>Articles: </h1>
<p>
    <%= link_to 'Create new article', articles_path %>
</p>
<table>
    <tr>
        <th> Title </th>
        <th> Description </th>
        <th> Actions </th>
    </tr>
    <% @articles.each do |a| %>
        <tr>
            <td> <%= a.title %> </td>
            <td> <%= a.description %> </td>
            <td> <%= link_to 'View', article_path(a) %>
                 <%= link_to 'Edit', edit_article_path(a) %> 
                 <%# <%= link_to 'Delete', destroy_article_path(a) %>
            </td>
        </tr>
    <% end %>
</table>

app/views/articles/new.html.erb
<% if @article.errors.any? %>
  <h2>Found the following errors when creating your article:</h2>
  <ul>
    <% @article.errors.full_messages.each do |err_msg| %>
        <li> <%= err_msg %> </li>
    <% end %>
  </ul>
<% end %>

  <h1>Create a new article</h1>
<div>
  <%= form_for @article do |f|%>
    <p>
        <%= f.label :title %>
        </br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %>
        </br>
        <%= f.text_area :description %>
    </p>
    <%= f.submit %>
  <% end %>
</div>
</br></br>
<%= link_to 'Home', root_path %>

app/views/articles/show.html.erb
<h1>Showing selected article:</h1>
<div>
    <p>
        Title: <%= @article.title %>
        </br>
        Description: <%= @article.description %>
        </br>
    </p>
</div>
</br></br>

<%= link_to 'Articles List', articles_path %>
</br>
<%= link_to 'Edit this article', edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
 <% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
 <% end %>
 <%= yield %>
</body>
</html>

app/views/welcome/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<%= link_to 'Home', root_path %>
<h1>About:</h1>
<div>
  <p>This website is built for learning and practing purposes on learning Ruby on Rails through <a href="https://www.udemy.com/the-complete-ruby-on-rails-developer-course">The Complete Ruby on Rails Developer Course</a></p>
</div>
</body>
</html>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<h1>Welcome to my first web page!</h1>
<%= link_to 'About', about_path %>
<div>
  <img src="https://cdn-images-1.medium.com/max/2600/1*0KFB17_NGTPB0XWyc4BSgQ.jpeg">
  <p>Hello! My Name is Monique and I am a Software Enginner. I have learned programming with Java, then I have worked with C# and Python languages. Now I am trying to learn <strong>Ruby on Rails</strong> and Frond End development since the company I currently work for make use of them.</p>
</div>
</body>
</html>